[package]
name = "aws-cli-account-info"
version = "0.1.0"
edition = "2024"
license = "MIT"
author = "revolko (Juraj Paluba)"
description = "AWS CLI prompt info"

[dependencies]
anyhow = "1"
shellexpand = "3.1"
yaml-rust = "0.4"
